### ISSUE TITLE
Crash when opening file dialog in Arch/Manjaro Linux

### ISSUE THREAD

**Issue by voncose** [armory3d/armorpaint#179]
similar to https://github.com/armory3d/armorpaint/issues/63 (windows)

Armorpaint v0.7 (2019-09-09) - 6784b3b

Arch 5.2.8-arch1-1-ARCH #1

I am able to drag in fbx files manually without issue (via thunar in fluxbox). Attempting to click save or open via File menu (also tried hotkeys Ctrl + s or Ctrl + o) or clicking import via materials crashes with 'Segmentation fault (core dumped)'

Per https://github.com/armory3d/armorpaint/issues/63 I attempted to run as superuser and sudo (to bypass possible permissions issue) with no change.

**Comment by luboslenco** [comment]
ArmorPaint uses Zenity on Linux to open a file browser, I am guessing something goes wrong there - will investigate. Thanks for report!

**Comment by luboslenco** [comment]
Added a new `Edit - Preferences - Native File Browser` option in https://github.com/armory3d/armorpaint/commit/5cbfcf68d6ab01e7000f00a1a2205bb8c5784a22. Disabling this option will make ArmorPaint use it's own, primitive file browser and should at least make it possible to export the painted textures.

Will push out updated Linux builds asap. Keeping the issue open as this is only a workaround and not a proper fix yet.

**Comment by DjoleDzele** [comment]
Awesome! Tested now with updated repo, unchecked the Native Browser option in settings, and exporting / importing stuff from the main menu seems to work good. I tried also those separate import buttons on the right side menus (materials, meshes, viewport) they dont seem to react at all now but at least it works good from the main menu

**Comment by luboslenco** [comment]
Great, many thanks for testing!

>  I tried also those separate import buttons on the right side menus (materials, meshes, viewport) they dont seem to react at all

Fixed now as well.

**Comment by luboslenco** [comment]
Any luck with latest 0.8 dev builds?

**Comment by DjoleDzele** [comment]
I tested 0.8 now, the issue persists in my case, but it still works normally if disable "native browser" in settings. Also it seems that changed settings are not remembered when i start the program next time, i need to deselect it again each time, not sure if it was like that before

**Comment by luboslenco** [comment]
Any luck with latest 0.8 dev builds? ArmorPaint now uses gtk to open the file browser window.

**Comment by DjoleDzele** [comment]
Hmm, I removed everything and tried to do fresh compiling, and now i actually can't get through compile process, I get stuck on this part
->> node Kinc/make -g opengl --compiler clang --compile

**Comment by luboslenco** [comment]
Thanks for giving it a spin - pushed a fix attempt now. https://github.com/armory3d/armorcore/commit/5f7e6dcfcd89c7ba1c2b3bece1d4e24bd05754f4

**Comment by DjoleDzele** [comment]
Compiling is working now, and GTK file browser works now as well it seems :D

**Comment by luboslenco** [comment]
😮 🎉🎉 Glad to hear!
