### ISSUE TITLE
Lots of distortion when importing mesh

### ISSUE THREAD

**Issue by zrsigs** [armory3d/armorpaint#240]
When I import a mesh into armor paint, it has lots of static or distortion on it. And when I paint on the surface of the mesh it is painting on multiple spots at the same time. What am I doing wrong?

**Comment by luboslenco** [comment]
Hi, are you on the latest armorpaint 0.7dev version? It should be resolved there (https://github.com/armory3d/armorpaint/issues/232#issuecomment-564094069). If you are already on the latest, are you able to share the file which causes issue? I also mention how to build non-overlapping UVs at https://github.com/armory3d/armorpaint/issues/232#issuecomment-564094069, to prevent painting multiple spots at once.

**Comment by zrsigs** [comment]
> 
> 
> Hi, are you on the latest armorpaint 0.7dev version? It should be resolved there ([#232 (comment)](https://github.com/armory3d/armorpaint/issues/232#issuecomment-564094069)). If you are already on the latest, are you able to share the file which causes issue? I also mention how to build non-overlapping UVs at [#232 (comment)](https://github.com/armory3d/armorpaint/issues/232#issuecomment-564094069), to prevent painting multiple spots at once.

I am on the latest version. I just downloaded it last night from their website. Let me try some of these suggestions and Ill post the file if I am still having issues.

**Comment by luboslenco** [comment]
Please feel welcome to reopen if issue persists in 0.7.
