### ISSUE TITLE
Custome node not working in conjunction with him

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#499]
win 10 64 bit
v0.8 (2020-07-11) - e3be018

good day! Accidentally noticed such a feature.
If you run any custom node and connect it with its copy, then there is no result.
For example, I took the standard plugin Hello Nodier. I made a copy of this node and connected it to it. As a result, the node stopped working.
![1](https://user-images.githubusercontent.com/65244629/87587117-5b9ec480-c6ea-11ea-9191-a46045edbff7.jpg)
![2](https://user-images.githubusercontent.com/65244629/87587121-5ccff180-c6ea-11ea-9291-ca430e29c47e.jpg)
![3](https://user-images.githubusercontent.com/65244629/87587123-5ccff180-c6ea-11ea-9614-4e85cd8c1b14.jpg)
![4](https://user-images.githubusercontent.com/65244629/87587125-5d688800-c6ea-11ea-8261-9dc88b646880.jpg)

**Comment by luboslenco** [comment]
👍  Fixed now at https://github.com/armory3d/armorpaint/commit/e5ff59f6ecc94ae46fa0f0cf3eabb9c4aca9035d.

**Comment by AlexKiryanov** [comment]
good day! I have a happy day today! ??? Thank you so much!!!!

**Comment by AlexKiryanov** [comment]
Good morning Lubos!
I watched it! Yes, now the custom node works with each other. But I tried to fix my node with new code and it still doesn't want to work with itself.
Here is the code:
[normalMixNode.txt](https://github.com/armory3d/armorpaint/files/5249186/normalMixNode.txt)
Good morning Lubos!
I watched it! Yes, now the custom node works with each other. But I tried to fix my nodepod with new code, and it still doesn't want to work with itself.
Node code in the application.
What I noticed new.
Now variables from the input can work directly in the code. There is no need to translate them from ic to glsl (example: float nimbus = $ (factor)) For some reason, it didn’t work for me on a straight line.
You have renamed the material to MaterialParser
This is also a new line default_value: new Float32Array ([0.8, 0.8, 0.8, 1.0])
She is on the hike and is responsible for ensuring that the nodes can connect durg with durg. I can really be wrong, I'm not a programmer. I study.
But there may be a reason in this line, I use variables of the vector type and here is an array of numbers. ? mmm
And here's a new line let my_out = arm.MaterialParser.node_name (node) + "_out";
She, too, I will understand so much for the functioning of the nodes with each other.
Please see what could I have gone wrong?
Separately, the nodes work but not with each other.
By the way, sockets are also cool that we have now)
And forgive me, but I'll ask ... and with the texture shift in the custom node, you have not yet figured out what you can do?
Thank you so much! And a good day!
